### ISSUE TITLE
Some outdated information on Friday Hacks FAQ page

### ISSUE THREAD

**Issue by staceytay** [nushackers/nushackers-site#22]
We should update http://nushackers.com/fridayhacks/ to reflect that we don't always hold our FH talks in UTown.

**Comment by varunpatro** [comment]
https://github.com/nushackers/nushackers-site/pull/19#discussion-diff-75634169R28 address this to some extent. What do you think?

**Comment by unusep** [comment]
Resolved with [#19 (diff)](https://github.com/nushackers/nushackers-site/pull/19#discussion-diff-75634169R28)
