### ISSUE TITLE
Complete and ship (Dec and h&r) plans

### ISSUE THREAD

**Issue by ngzhian** [nushackers/nushackers-site#32]
GOGOGOGOGO

**Comment by ngzhian** [comment]
Why is this closed btw? @jethrokuan

**Comment by jethrokuan** [comment]
oh I guess H&R is over... so this issue didn't really make sense anymore.

**Comment by ngzhian** [comment]
Oh okay make sense. This issue refers to work that was to be done by last Dec and could be done during h&r. But it hasn't been done yet so I'm reopening and changing the title to clairfy

**Comment by jethrokuan** [comment]
Anywhere we can see said plans?
