### ISSUE TITLE
Div is misaligned on landing page.

### ISSUE THREAD

**Issue by sushinoya** [nushackers/nushackers-site#67]
The div containing the text "_We're building a community of passionate hackers..._" gets misaligned if the number of friday hacks in the right column is too few.

Usual Behaviour: 
<img width="1185" alt="screen shot 2017-08-03 at 12 28 41 pm" src="https://user-images.githubusercontent.com/23443586/28906095-b9e9e410-7847-11e7-97ca-68e2b22b2f22.png">

Behaviour when only one or two friday hacks are listed:
<img width="1020" alt="screen shot 2017-08-03 at 12 28 49 pm" src="https://user-images.githubusercontent.com/23443586/28906103-cdece494-7847-11e7-8009-5c306e339a81.png">

Steps to replicate: Run jekyll locally -> remove all but one friday hacks from _data/friday_hacks.yml -> Go to landing page

**Comment by unusep** [comment]
@suyashshekhar can you verify if this issue is still present on our website revamp on the develop branch?

**Comment by suyashshekhar** [comment]
@unusep I only checked it on master. Will check asap

**Comment by li-kai** [comment]
There's no more special footer at the bottom. The introduction with "What we do" is a better replacement; people know our purpose on visiting the site.
